export const pages = [
  "dashboard",
  "patients",
  "patient-details",
  "drivers",
  "driver-details",
  "employees",
  "employee-details",
  "upload",
  "review_import",
  "account",
  "billing",
  "notifications",
  "founder",
  "accept-invite",
  "trips",
  "trip-details",
  "client-credits",
  "broker-integrations",
  "driver-history",
  "medicaid-billing",
  "live-tracking",
  "companies",
  "reset-password",
  "fees",
  "summary",
] as const;

export type Page = (typeof pages)[number];
