import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { format } from "date-fns";
import { formatInUserTimezone } from "@/lib/timezone";
import { VEHICLE_TYPE_NEEDS } from "@/lib/constants";
import { TRIP_TYPES } from "@/components/trips/trip-utils";
import type { SummaryTrip, FilterState } from "./types";

interface PDFGeneratorParams {
  trips: SummaryTrip[];
  filters: FilterState;
  timezone: string;
  orgName: string;
  generatedBy: string;
  userRole: string;
}

export function generateSummaryPDF({
  trips,
  filters,
  timezone,
  orgName,
  generatedBy,
  userRole,
}: PDFGeneratorParams) {
  const doc = new jsPDF({
    orientation: "landscape",
    unit: "mm",
    format: "a4",
  });

  const primaryColor: [number, number, number] = [61, 90, 61];
  const textColor: [number, number, number] = [15, 23, 42];
  const mutedTextColor: [number, number, number] = [100, 116, 139];

  // Header
  doc.setFontSize(22);
  doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  doc.text(orgName || "MediTrans", 14, 20);

  doc.setFontSize(10);
  doc.setTextColor(mutedTextColor[0], mutedTextColor[1], mutedTextColor[2]);
  doc.text("Trips Summary Report", 14, 26);

  // Report Info
  doc.setFontSize(10);
  doc.setTextColor(textColor[0], textColor[1], textColor[2]);

  const infoY = 35;
  doc.text(
    `Period: ${format(new Date(filters.startDate), "MMM dd, yyyy")} - ${format(new Date(filters.endDate), "MMM dd, yyyy")}`,
    14,
    infoY,
  );
  doc.text(`Generated By: ${generatedBy}`, 14, infoY + 5);
  doc.text(`Role: ${userRole || "Admin"}`, 14, infoY + 10);
  doc.text(
    `Generated On: ${format(new Date(), "MMM dd, yyyy HH:mm")}`,
    280,
    infoY,
    { align: "right" },
  );
  doc.text(`Total Trips: ${trips.length}`, 280, infoY + 5, {
    align: "right",
  });

  // Filters
  const hasFilters =
    filters.selectedVehicleTypes.length > 0 ||
    filters.selectedWaiverTypes.length > 0 ||
    filters.selectedReferredBy.length > 0 ||
    filters.selectedSalStatuses.length > 0 ||
    filters.selectedTripPurposes.length > 0;

  if (hasFilters) {
    const filterY = infoY + 15;
    doc.setFontSize(9);
    doc.setTextColor(mutedTextColor[0], mutedTextColor[1], mutedTextColor[2]);
    doc.text("Filters Applied:", 14, filterY);
    const parts: string[] = [];
    if (filters.selectedVehicleTypes.length > 0) {
      parts.push(
        `Vehicle: ${filters.selectedVehicleTypes.map((v) => VEHICLE_TYPE_NEEDS.find((t) => t.value === v)?.label || v).join(", ")}`,
      );
    }
    if (filters.selectedWaiverTypes.length > 0) {
      parts.push(`Waiver: ${filters.selectedWaiverTypes.join(", ")}`);
    }
    if (filters.selectedReferredBy.length > 0) {
      parts.push(`Referred By: ${filters.selectedReferredBy.join(", ")}`);
    }
    if (filters.selectedSalStatuses.length > 0) {
      parts.push(
        `SAL Status: ${filters.selectedSalStatuses.map((s) => s.charAt(0).toUpperCase() + s.slice(1)).join(", ")}`,
      );
    }
    if (filters.selectedTripPurposes.length > 0) {
      parts.push(
        `Trip Purpose: ${filters.selectedTripPurposes.map((v) => TRIP_TYPES.find((t) => t.value === v)?.label || v).join(", ")}`,
      );
    }
    doc.text(parts.join("  |  "), 14, filterY + 4);
  }

  // Table
  const tableStartY = hasFilters ? infoY + 25 : 55;

  const tableData = trips.map((trip, index) => {
    const pickupTime = formatInUserTimezone(
      trip.pickup_time,
      timezone,
      "MMM dd, yyyy HH:mm",
    );
    const duration =
      trip.actual_duration_minutes || trip.duration_minutes || "";

    return [
      (index + 1).toString(),
      trip.id.slice(0, 8),
      trip.trip_type || "N/A",
      pickupTime,
      trip.pickup_location || "",
      trip.dropoff_location || "",
      duration ? `${duration} min` : "N/A",
      trip.actual_distance_miles ? `${trip.actual_distance_miles} mi` : "",
      trip.billing_details?.total_cost
        ? `$${trip.billing_details.total_cost.toFixed(2)}`
        : "",
      trip.status.replace("_", " "),
      trip.driver?.full_name || "Unassigned",
      trip.driver?.vehicle_info || "N/A",
      trip.patient?.full_name || "N/A",
    ];
  });

  autoTable(doc, {
    startY: tableStartY,
    head: [
      [
        "#",
        "ID",
        "Type",
        "Date/Time",
        "Pickup",
        "Dropoff",
        "Duration",
        "Dist",
        "Cost",
        "Status",
        "Driver",
        "Vehicle",
        "Patient",
      ],
    ],
    body: tableData,
    theme: "striped",
    headStyles: {
      fillColor: primaryColor,
      textColor: [255, 255, 255],
      fontSize: 8,
      fontStyle: "bold",
    },
    bodyStyles: {
      fontSize: 7,
      cellPadding: 2,
    },
    columnStyles: {
      0: { cellWidth: 10 },
      1: { cellWidth: 15 },
      2: { cellWidth: 15 },
      3: { cellWidth: 25 },
      4: { cellWidth: 35 },
      5: { cellWidth: 35 },
      6: { cellWidth: 15 },
      7: { cellWidth: 12 },
      8: { cellWidth: 15 },
      9: { cellWidth: 18 },
      10: { cellWidth: 25 },
      11: { cellWidth: 20 },
      12: { cellWidth: 25 },
    },
    didParseCell: (data) => {
      if (data.section === "body" && data.column.index === 9) {
        const row = data.row.raw as any;
        const status = row[9] as string;
        if (status.includes("completed")) {
          data.cell.styles.textColor = [16, 185, 129] as [number, number, number];
          data.cell.styles.fontStyle = "bold";
        } else if (status.includes("cancelled")) {
          data.cell.styles.textColor = [239, 68, 68] as [number, number, number];
        } else if (status.includes("in progress")) {
          data.cell.styles.textColor = [59, 130, 246] as [number, number, number];
          data.cell.styles.fontStyle = "bold";
        }
      }
    },
  });

  doc.save(`trips_summary_${filters.startDate}_to_${filters.endDate}.pdf`);
}
