import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { format } from "date-fns";
import { formatInUserTimezone } from "@/lib/timezone";
import { VEHICLE_TYPE_NEEDS } from "@/lib/constants";
import { TRIP_TYPES } from "@/components/trips/trip-utils";
import type { SummaryTrip, FilterState } from "./types";

interface PDFGeneratorParams {
  trips: SummaryTrip[];
  filters: FilterState;
  timezone: string;
  orgName: string;
  generatedBy: string;
  userRole: string;
  reportTitle?: string;
  subjectName?: string;
}

export function generateSummaryPDF({
  trips,
  filters,
  timezone,
  orgName,
  generatedBy,
  userRole,
  reportTitle,
  subjectName,
}: PDFGeneratorParams) {
  const doc = new jsPDF({
    orientation: "landscape",
    unit: "mm",
    format: "a4",
  });

  const primaryColor: [number, number, number] = [61, 90, 61];
  const textColor: [number, number, number] = [15, 23, 42];
  const mutedTextColor: [number, number, number] = [100, 116, 139];

  doc.setFontSize(22);
  doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  doc.text(orgName || "MediTrans", 14, 20);

  doc.setFontSize(10);
  doc.setTextColor(mutedTextColor[0], mutedTextColor[1], mutedTextColor[2]);
  const displayTitle = reportTitle 
    ? `${reportTitle}${subjectName ? ` for ${subjectName}` : ""}`
    : "Trips Summary Report";
  doc.text(displayTitle, 14, 26);

  // Report Info
  doc.setFontSize(10);
  doc.setTextColor(textColor[0], textColor[1], textColor[2]);

  const periodY = 35;
  // Format dates strictly as local strings to prevent UTC shifts in the header
  const startDateStr = format(new Date(`${filters.startDate}T00:00:00`), "MMM dd, yyyy");
  const endDateStr = format(new Date(`${filters.endDate}T00:00:00`), "MMM dd, yyyy");
  
  doc.text(
    `Period: ${startDateStr} - ${endDateStr}`,
    14,
    periodY,
  );
  doc.text(`Generated By: ${generatedBy}`, 14, periodY + 5);
  doc.text(`Role: ${userRole || "Admin"}`, 14, periodY + 10);
  doc.text(
    `Generated On: ${format(new Date(), "MMM dd, yyyy HH:mm")}`,
    280,
    periodY,
    { align: "right" },
  );
  doc.text(`Total Trips: ${trips.length}`, 280, periodY + 5, {
    align: "right",
  });

  // Filters
  const hasFilters =
    filters.selectedVehicleTypes.length > 0 ||
    filters.selectedWaiverTypes.length > 0 ||
    filters.selectedReferredBy.length > 0 ||
    filters.selectedSalStatuses.length > 0 ||
    filters.selectedTripPurposes.length > 0 ||
    filters.selectedTripStatuses.length > 0;

  if (hasFilters) {
    const filterY = periodY + 15;
    doc.setFontSize(9);
    doc.setTextColor(mutedTextColor[0], mutedTextColor[1], mutedTextColor[2]);
    doc.text("Filters Applied:", 14, filterY);
    const parts: string[] = [];
    if (filters.selectedVehicleTypes.length > 0) {
      parts.push(
        `Vehicle: ${filters.selectedVehicleTypes.map((v) => VEHICLE_TYPE_NEEDS.find((t) => t.value === v)?.label || v).join(", ")}`,
      );
    }
    if (filters.selectedWaiverTypes.length > 0) {
      parts.push(`Waiver: ${filters.selectedWaiverTypes.join(", ")}`);
    }
    if (filters.selectedReferredBy.length > 0) {
      parts.push(`Referred By: ${filters.selectedReferredBy.join(", ")}`);
    }
    if (filters.selectedSalStatuses.length > 0) {
      parts.push(
        `SAL Status: ${filters.selectedSalStatuses.map((s) => s.charAt(0).toUpperCase() + s.slice(1)).join(", ")}`,
      );
    }
    if (filters.selectedTripPurposes.length > 0) {
      parts.push(
        `Trip Purpose: ${filters.selectedTripPurposes.map((v) => TRIP_TYPES.find((t) => t.value === v)?.label || v).join(", ")}`,
      );
    }
    if (filters.selectedTripStatuses.length > 0) {
      parts.push(
        `Trip Status: ${filters.selectedTripStatuses.map((v) => v.charAt(0).toUpperCase() + v.slice(1).replace("_", " ")).join(", ")}`,
      );
    }
    doc.text(parts.join("  |  "), 14, filterY + 4);
  }

  // Table
  const tableStartY = hasFilters ? periodY + 25 : 55;

  const tableData = trips.map((trip, index) => {
    const pickupTime = formatInUserTimezone(
      trip.pickup_time,
      timezone,
      "MMM dd, yyyy HH:mm",
    );
    const duration =
      trip.actual_duration_minutes || trip.duration_minutes || "";

    return [
      (index + 1).toString(),
      trip.id.slice(0, 8),
      trip.trip_type || "N/A",
      pickupTime,
      trip.pickup_location || "",
      trip.dropoff_location || "",
      duration ? `${duration} min` : "N/A",
      trip.actual_distance_miles 
        ? `${trip.actual_distance_miles} mi` 
        : trip.distance_miles 
          ? `${trip.distance_miles} mi` 
          : "",
      trip.status.replace("_", " "),
      trip.driver?.full_name || "Unassigned",
      trip.driver?.vehicle_info || "N/A",
      trip.patient?.full_name || "N/A",
    ];
  });

  // Calculate totals
  const totalDistance = trips.reduce((sum, trip) => sum + (trip.actual_distance_miles || trip.distance_miles || 0), 0);
  const totalDuration = trips.reduce((sum, trip) => sum + (trip.actual_duration_minutes || trip.duration_minutes || 0), 0);

  const footerData = [
    [
      { content: "TOTALS", colSpan: 6, styles: { halign: "center", valign: "middle", fontStyle: "bold" } },
      { content: `${totalDuration} min`, styles: { halign: "center", valign: "middle", fontStyle: "bold", cellPadding: { left: 1, right: 1 } } },
      { content: `${totalDistance.toFixed(1)} mi`, styles: { halign: "center", valign: "middle", fontStyle: "bold", cellPadding: { left: 1, right: 1 } } },
      { content: `${trips.length} trips`, colSpan: 4, styles: { halign: "center", valign: "middle", fontStyle: "bold" } },
    ],
  ];

  autoTable(doc, {
    startY: tableStartY,
    head: [
      [
        "#",
        "ID",
        "Type",
        "Date/Time",
        "Pickup",
        "Dropoff",
        "Duration",
        "Dist",
        "Status",
        "Driver",
        "Vehicle",
        "Patient",
      ],
    ],
    body: tableData,
    foot: footerData as any,
    theme: "striped",
    headStyles: {
      fillColor: primaryColor,
      textColor: [255, 255, 255],
      fontSize: 8,
      fontStyle: "bold",
      halign: "center",
      valign: "middle",
    },
    bodyStyles: {
      fontSize: 7,
      cellPadding: 2,
      halign: "center",
      valign: "middle",
    },
    footStyles: {
      fillColor: [241, 245, 249],
      textColor: textColor,
      fontSize: 8,
      fontStyle: "bold",
      halign: "center",
      valign: "middle",
    },
    columnStyles: {
      0: { cellWidth: 8 },
      1: { cellWidth: 16 },
      2: { cellWidth: 22 }, // Type
      3: { cellWidth: 23 }, // Date/Time
      4: { cellWidth: 36 }, // Pickup
      5: { cellWidth: 36 }, // Dropoff
      6: { cellWidth: 16, cellPadding: { left: 0.5, right: 0.5 } }, // Duration
      7: { cellWidth: 16, cellPadding: { left: 0.5, right: 0.5 } }, // Dist
      8: { cellWidth: 20 }, // Status
      9: { cellWidth: 26 }, // Driver
      10: { cellWidth: 20 }, // Vehicle
      11: { cellWidth: 28 }, // Patient
    },
    didParseCell: (data) => {
      if (data.section === "body" && data.column.index === 8) {
        const row = data.row.raw as any;
        const status = row[8] as string;
        if (status.includes("completed")) {
          data.cell.styles.textColor = [16, 185, 129] as [number, number, number];
          data.cell.styles.fontStyle = "bold";
        } else if (status.includes("cancelled")) {
          data.cell.styles.textColor = [239, 68, 68] as [number, number, number];
        } else if (status.includes("in progress")) {
          data.cell.styles.textColor = [59, 130, 246] as [number, number, number];
          data.cell.styles.fontStyle = "bold";
        }
      }
    },
  });

  const fileNameSubject = subjectName ? `_${subjectName.replace(/\s+/g, "_")}` : "";
  const fileType = reportTitle ? reportTitle.toLowerCase().replace(/\s+/g, "_") : "trips_summary";
  doc.save(`${fileType}${fileNameSubject}_${filters.startDate}_to_${filters.endDate}.pdf`);
}
